apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: grupo1
  labels:
    name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'api-azure'
        static_configs:
          - targets: ['api-azure:5000']