apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-disk-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-csi  # Usa 'managed-csi' ou 'azure-disk' se esse não existir
  resources:
    requests:
      storage: 5Gi
